services:
  app:
    image: node:24
    working_dir: /app
    volumes:
      - ./:/app # Conecta o diretório atual (./) ao diretório /app no contêiner
    ports:
      - "5173:5173"
      - "4173:4173"
    tty: true
    stdin_open: true
